### ISSUE TITLE
Import error, compatibility issue with seaborn?

### ISSUE THREAD

**Issue by fegarcia-bcam** [pog87/PtitPrince#30] opened 2022-10-05 18:15 UTC
Hi there!

Foremost, thanks for developing this very nice package for visualization.
I was using it some time ago, but now I'm encountering problems -- probably related to having to reinstall environments.

So now, when I try to import PtitPrince, I get the following:
`ImportError: cannot import name 'categorical_order' from 'seaborn._core'`
(line 20)

I have tried with **seaborn** manually set to version 0.10 (as mentioned in the Readme), also 0.11 (as in the requirements.txt file), and even 0.12 (the most recent version, which gets auto installed by default if I don't have seaborn pre-installed in the environment before PtitPrince).

For reference, if it may be useful, I'm installing PtitPrince with your instructions
`conda install -c conda-forge ptitprince`

**Comment by fegarcia-bcam** [comment] 2022-10-05 19:05
I kind of solved it myself. For some reason, installing PtitPrince with `conda` made it go to **ptitprince** version 0.25 and **seaborn** version 0.12; whereas with `pip` they went to versions 0.26 and 0.11, respectively.

**Comment by pog87** [comment] 2022-10-06 07:29
The lastest version solves this issue, but I can't figure out why it is not on conda-forge yet.

I need help about this.... @sappelhoff isn't the update on conda-forge an automatic process? Thanks for helping

**Comment by sappelhoff** [comment] 2022-10-08 10:48
Let's see if this is fixed with

- https://github.com/conda-forge/ptitprince-feedstock/pull/9

**Comment by sappelhoff** [comment] 2022-10-08 11:09
@pog87 ah, the problem is that for ptitprince `0.2.6`, only wheels are available, not the source distribution (`.tar.gz`), see: https://pypi.org/project/ptitprince/0.2.6/#files

This can be fixed by building the sdist and then uploading that

```
pip install -U setuptools wheel twine
python setup.py sdist
# make sure in the dist folder there is only the .tar.gz dist ... delete all others
twine upload dist/*
# enter credentials
# done
```

It'd be good practice to always upload both, wheels and sdist

**Comment by sappelhoff** [comment] 2022-10-12 18:09
@pog87 if you give me "maintainer" rights on pypi, I can do this for you in case you are swamped with other stuff. I am `sappelhoff` on pypi: https://pypi.org/user/sappelhoff/

**Comment by pog87** [comment] 2022-10-13 08:37
@sappelhoff maintainer permission granted, thanks a lot

**Closed by pog87** 2022-10-13 08:37 UTC
